name: 'Hello World'
description: 'Greet someone'
outputs:
  text:
    description: "Greeting"
    value: ${{ steps.greeting.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: Set greeting text
      id: greeting
      run: echo "text=world" >> $GITHUB_OUTPUT
      shell: bash

    - name: Say ji
      run: echo Hi
      shell: bash

    - name: Return data
      uses: actions/github-script@v7
      with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: "${{ github.repository }}".split("/")[0],
              repo: "${{ github.repository }}".split("/")[1],
              event_type: "return_data_to_ubiquibot_kernel",
              client_payload: {
                output: `{ "test_output": "output-plugin-A" }`,
              },
            });
