on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4

      - id: greeting
        uses: ./

      - run: echo greeting "$GREETING"
        shell: bash
        env:
          GREETING: ${{ steps.greeting.outputs.text }}

      - name: Return data
        uses: actions/github-script@v7
        with:
            script: |
              await github.rest.repos.createDispatchEvent({
                owner: "${{ github.repository }}".split("/")[0],
                repo: "${{ github.repository }}".split("/")[1],
                event_type: "return_data_to_ubiquibot_kernel",
                client_payload: {
                  output: `{ "test_output": "output-plugin-A" }`,
                },
              });
