on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4

      - id: greeting
        uses: ./

      - run: echo greeting "$GREETING"
        shell: bash
        env:
          GREETING: ${{ steps.greeting.outputs.text }}
